// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Calculate_leavedays extends CustomJavaAction<java.lang.Long>
{
	private java.util.Date Start_date;
	private java.util.Date End_date;

	public Calculate_leavedays(IContext context, java.util.Date Start_date, java.util.Date End_date)
	{
		super(context);
		this.Start_date = Start_date;
		this.End_date = End_date;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		long diffInMillis = this.End_date.getTime() - this.Start_date.getTime();
		long days = (int) (diffInMillis / (1000 * 60 * 60 * 24));
		return days;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Calculate_leavedays";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
