// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class EmpCode extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Long number;

	public EmpCode(IContext context, java.lang.Long number)
	{
		super(context);
		this.number = number;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		

		// Safely handle null input
		if (number == null)
			return 0L;

		// Convert Long to primitive long
		long num = number.longValue();

		// Compute square using Math.pow and cast result to long
		long squared = (long) Math.pow(num, 3);

		// Return result as Long
		return Long.valueOf(squared);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "EmpCode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
